@startuml
!define table(x) class x << (T,#FFAAAA) >>
hide methods
hide stereotypes

table(Users) {
    PK user_ID
    FK wallet_ID
    String name
    String email
}

table(Products) {
    PK product_ID
    String name
    blob image
    float price
    int stock
    String subProductCategory
}

table(Favorites) {
    FK user_ID
    FK product_ID
}

table(Wallets) {
    PK wallet_ID
    int fonds
}

table(CreditCards) {
    PK creditCard_ID
    FK wallet_ID
}

table(Coupons) {
    PK coupon_ID
    FK wallet_ID
}

table(SubProductCategorys) {
    String category
    blob image
}

table(ProductCategorys) {
    String category
    blob image
}

Wallets ||--|| Users
Wallets }o--|| CreditCards
Wallets }o--|| Coupons
Favorites ||--o{ Users
Favorites ||--o{ Products

@enduml